apiVersion: v1
kind: Template
labels:
  template: f8a-3scale-connect-api
metadata:
  name: f8a-3scale-connect-api
  annotations:
    description: f8a-3scale-connect-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-3scale-connect-api
    name: f8a-3scale-connect-api
  spec:
    selector:
      service: f8a-3scale-connect-api
    template:
      metadata:
        labels:
          service: f8a-3scale-connect-api
      spec:
        containers:
        - env:
          - name: GUNICORN_CMD_ARGS
            value: "${GUNICORN_CMD_ARGS}"
          - name: THREE_SCALE_API_SERVICE_ID
            valueFrom:
              secretKeyRef:
                name: 3scale-connect-api
                key: three-scale-api-service-id
          - name: THREE_SCALE_API_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: 3scale-connect-api
                key: three-scale-api-access-key
          - name: THREE_SCALE_API_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: 3scale-connect-api
                key: three-scale-api-account-id
          - name: THREE_SCALE_API_HOST_URL
            valueFrom:
              secretKeyRef:
                name: 3scale-connect-api
                key: three-scale-api-host-url
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-3scale-connect-api
          ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/v1/readiness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/liveness
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-3scale-connect-api
    name: f8a-3scale-connect-api
  spec:
    ports:
    - name: "32000"
      port: 32000
      protocol: TCP
      targetPort: 5000
    selector:
      service: f8a-3scale-connect-api
- apiVersion: v1
  kind: Route
  metadata:
    name: f8a-3scale-connect-api
  spec:
    host: ${BAYESIAN_API_HOSTNAME}
    to:
      kind: Service
      name: f8a-3scale-connect-api

parameters:
- description: A hostname where the 3 Scale admin gateway API should be exposed (will be auto-generated if empty)
  displayName: 3 Scale API hostname
  required: false
  name: BAYESIAN_API_HOSTNAME

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "openshiftio/rhel-fabric8-analytics-f8a-3scale-connect-api"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "3"

- description: Settings for Gunicorn
  displayName: Settings for Gunicorn
  required: true
  name: GUNICORN_CMD_ARGS
  value: "-b :5000 --workers=4"

