apiVersion: v1
kind: Template
labels:
  template: f8a-3scale-admin-gateway
metadata:
  name: f8a-3scale-admin-gateway
  annotations:
    description: f8a-3scale-admin-gateway
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: f8a-3scale-admin-gateway
    name: f8a-3scale-admin-gateway
  spec:
    selector:
      service: f8a-3scale-admin-gateway
    template:
      metadata:
        labels:
          service: f8a-3scale-admin-gateway
      spec:
        containers:
        - env:
          - name: GUNICORN_CMD_ARGS
            value: "${GUNICORN_CMD_ARGS}"
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: f8a-3scale-admin-gateway
          - name: THREE_SCALE_API_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: 3scale
                key: three_scale_api_access_key
          - name: THREE_SCALE_API_HOST_URL
            valueFrom:
              secretKeyRef:
                name: 3scale
                key: three_scale_api_host_url
          - name: THREE_SCALE_API_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: 3scale
                key: three_scale_api_account_id
        ports:
          - containerPort: 5000
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: f8a-3scale-admin-gateway
    name: f8a-3scale-admin-gateway
  spec:
    ports:
    - name: "32000"
      port: 32000
      protocol: TCP
      targetPort: 5000
    selector:
      service: f8a-3scale-admin-gateway
- apiVersion: v1
  kind: Route
  metadata:
    name: f8a-3scale-admin-gateway
  spec:
    host: ${BAYESIAN_API_HOSTNAME}
    to:
      kind: Service
      name: f8a-3scale-admin-gateway

parameters:
- description: A hostname where the 3 Scale admin gateway API should be exposed (will be auto-generated if empty)
  displayName: 3 Scale API hostname
  required: false
  name: BAYESIAN_API_HOSTNAME

- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics/3scale-admin-gateway"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"  # image-tag

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

- description: Settings for Gunicorn
  displayName: Settings for Gunicorn
  required: true
  name: GUNICORN_CMD_ARGS
  value: "-b :5000 --workers=4"
